---
spring:
  profile: local
route:
  inbound: 'file:/Users/Leslie/Documents/workspace/tradeprocess/src/main/resources/inbound?autoCreate=true'
  outbound: /Users/Leslie/Documents/workspace/tradeprocess/src/main/resources/outbound/outputReport.csv
